name: Deploy to GitHub Pages
on:
  push:
    branches: [main] # Hoặc tên branch chính của bạn
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Thư mục sau khi build (Vite là dist, React cũ là build)
          branch: gh-pages # GitHub sẽ tự tạo branch này để chứa web